# Generated by Django 5.2 on 2025-04-20 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('incendie', 'incendie'), ('accident', 'accident'), ('poublles', 'poublles'), ("fuites d'eau", "fuites d'eau")], default='incendie', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('En attante', 'En attante'), ('traitee', 'traitee')], max_length=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('catagorie', models.ForeignKey(default='non determine', on_delete=django.db.models.deletion.SET_DEFAULT, to='incidents_app.catagorie')),
            ],
        ),
    ]
