# Generated by Django 5.2 on 2025-04-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='etat',
            field=models.CharField(choices=[('En attante', 'En attante'), ('traite', 'traite')], max_length=12),
        ),
    ]
