# Generated by Django 5.2 on 2025-04-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents_app', '0002_alter_incident_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
